version: 2

# conda:
#     environment: install/environment.yml

sphinx:
    configuration: source/conf.py

build:
    image: latest

formats:
  - pdf

python:
    # version: 3.7
    install:
      # - requirements: source/requirements.txt
      - method: pip
        path: .
        # extra_requirements:
         # - sphinxcontrib-bibtex
    # system_packages: false
